version: "3.9"

services:
  flan-t5-service:
    container_name: flan-t5-container
    build:
      context: .
      dockerfile: Dockerfile
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [gpu]
    ports:
      - "5000:5000"
    volumes:
      - .:/app  # Monta tu carpeta local en /app dentro del contenedor
    environment:
      - FLASK_ENV=development  # Modo desarrollo para activar el auto-reload
      - FLASK_APP=app.py       # Define tu aplicación Flask principal
    working_dir: /app          # Asegura que el directorio de trabajo sea /app
    command: flask run --host=0.0.0.0 --port=5000
